GO
SET IDENTITY_INSERT [dbo].[Diagnostic] ON 

INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (1, 1, 3, 6, CAST(0x0000A80500000000 AS DateTime), N'Primer diagnostico TEST',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (2, 1, 2, 6, CAST(0x0000A80500000000 AS DateTime), N'Segundo diagnostico',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (3, 2, 3, 6, CAST(0x0000A80500000000 AS DateTime), N'Primer Diagnostico',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (4, 2, 2, 6, CAST(0x0000A80500000000 AS DateTime), N'Segundo diagnostico TEST',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (5, 2, 2, 6, CAST(0x0000A80500000000 AS DateTime), N'Tercer Diagnostico',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (6, 2, 3, 6, CAST(0x0000A80500000000 AS DateTime), N'Cuarto',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (7, 2, 4, 20, CAST(0x0000A80700000000 AS DateTime), N'Corte de uña',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (8, 2, 1, 4, CAST(0x0000A80500000000 AS DateTime), N'Prueba de validaciones',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (9, 2, 2, 20, CAST(0x0000A80700000000 AS DateTime), N'prueba',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (10, 2, 5, 20, CAST(0x0000A80700000000 AS DateTime), N'PRuebas',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (11, 7, 4, 20, CAST(0x0000A81A010C03CA AS DateTime), N'Encarnada',0,0,0,1)
INSERT [dbo].[Diagnostic] ([idDiagnostic], [IdPatient], [IdSpeciality], [IdProfessional], [Date], [Detail],[IdDestinationSpeciality],[IdDestinationProfessional],[DestinationRead],[Visible]) VALUES (12, 7, 4, 20, CAST(0x0000A81A010CDEC7 AS DateTime), N'dedo amputado  ....,,.',0,0,0,1)
SET IDENTITY_INSERT [dbo].[Diagnostic] OFF